layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

posts:
    title: Blog posts
projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 15
  exclude:
    archived: false
    forks: true
    projects:
    # - repo-name

social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
  # instagram: your_username
  # keybase: your_username
  linkedin: michelmake
  # mastodon: your_username
  # medium: your_username
  # stackoverflow: your_user_id
  # telegram: your_username
  # twitter: your_username
  # unsplash: your_username
  # vk: your_username
  website: https://www.cats.rwth-aachen.de/cms/CATS/Der-Lehrstuhl/Team/~ouyl/Make-Michel/lidx/1/
  # youtube: your_username

topics:
  - name: Google Scholar
    web_url: https://scholar.google.nl/citations?user=ipZgzLcAAAAJ&hl=nl
    image_url: https://upload.wikimedia.org/wikipedia/commons/thumb/c/c7/Google_Scholar_logo.svg/1200px-Google_Scholar_logo.svg.png

  - name: ResearchGate
    web_url: https://www.researchgate.net/profile/Michel_Make
    image_url: https://avatars0.githubusercontent.com/u/1073651?s=200&v=4

  - name: Arxiv
    web_url: https://arxiv.org/search/?searchtype=author&query=Make%2C+M
    image_url: https://cis.cornell.edu/sites/default/files/styles/square_thumbnail/public/Screen%20Shot%202018-09-04%20at%2010.17.51%20AM.png?itok=dxbUcd1u

  - name: M.Sc. Thesis
    web_url: https://repository.tudelft.nl/islandora/object/uuid:78d0c912-47fb-4efb-8953-ad33d8fc7e96?collection=education
    image_url: https://i.pinimg.com/originals/b3/9f/f8/b39ff8593414044bc1ab3a232e59cc12.jpg
